CREATE TABLE IF NOT EXISTS import_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(500) NOT NULL,
    source_path VARCHAR(1000) NOT NULL,
    checksum VARCHAR(128) NOT NULL,
    imported_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_import_history_checksum UNIQUE (checksum)
);